# Generated by Django 5.1.5 on 2025-01-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=256)),
                ('address', models.CharField(default='default', max_length=256)),
                ('phone', models.CharField(default='default', max_length=256)),
                ('email', models.EmailField(default='default', max_length=254)),
                ('type', models.CharField(choices=[('HOTEL', 'hotel'), ('HOSTEL', 'hostel'), ('APPARTMENT', 'appartment'), ('APPARTHOTEL', 'apparthotel')], default='HOTEL', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AppartHotel',
            fields=[
                ('accomodation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accomodation.accomodation')),
            ],
            bases=('accomodation.accomodation',),
        ),
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('accomodation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accomodation.accomodation')),
            ],
            bases=('accomodation.accomodation',),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('accomodation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accomodation.accomodation')),
            ],
            bases=('accomodation.accomodation',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('accomodation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accomodation.accomodation')),
            ],
            bases=('accomodation.accomodation',),
        ),
    ]
